set shell := ["bash", "-uc"]

startOnlineFedora:
    cd /home/archons/ArchonsWebsite/ArchonsWebsite
    ./venv/bin/pip3 install -r requirements.txt
    ./venv/bin/python3 manage.py makemigrations
    ./venv/bin/python3 manage.py migrate --run-syncdb
    nohup ./venv/bin/gunicorn ArchonsWebsite.wsgi:application --bind 0.0.0.0:8000
