startOnlineFedora:
    cd /home/archons/ArchonsWebsite/ArchonsWebsite
    git stash
    git pull
    pip3 install -r requirements.txt
    python3 manage.py makemigrations
    python3 manage.py migrate --run-syncdb
    sudo systemctl reload nginx
    nohup gunicorn ArchonsWebsite.wsgi:application --bind 0.0.0.0:8000